In [8]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine
import pandas as pd

In [4]:
# pip install sqlalchemy-redshift

Collecting sqlalchemy-redshift
  Downloading sqlalchemy_redshift-0.8.9-py2.py3-none-any.whl (36 kB)
Requirement already satisfied: SQLAlchemy<2.0.0,>=0.9.2 in /opt/conda/lib/python3.9/site-packages (from sqlalchemy-redshift) (1.4.35)
Requirement already satisfied: packaging in /opt/conda/lib/python3.9/site-packages (from sqlalchemy-redshift) (21.3)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.9/site-packages (from SQLAlchemy<2.0.0,>=0.9.2->sqlalchemy-redshift) (1.1.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.9/site-packages (from packaging->sqlalchemy-redshift) (3.0.7)
Installing collected packages: sqlalchemy-redshift
Successfully installed sqlalchemy-redshift-0.8.9
Note: you may need to restart the kernel to use updated packages.

In [35]:
import psycopg2
import pandas as pd
from pyspark.sql import SparkSession
from sqlalchemy import create_engine

appName = "PySpark PostgreSQL Example - via psycopg2"
master = "local"

spark = SparkSession.builder.master(master).appName(appName).getOrCreate()

In [36]:
url = 'redshift+psycopg2://dferreira:Y7*K.8jyNgdb@samsung-dl.chi3jsb4kpjs.us-east-1.redshift.amazonaws.com:5439/ssg?client_encoding=utf8'

In [46]:
# Create SQLAlchemy engine
engine = create_engine(url,echo=True)

In [48]:
engine.execute(sql)

2022-04-15 21:47:38,849 INFO sqlalchemy.engine.Engine select cad1.midia, cad26.midia,cad12.midia,
cad1.investiment as cad1inv, cad1.impressions as cad1imp,
cad3.investiment as cad3inv, cad3.impressions as cad3imp,
cad12.investiment as cad12inv, cad12.impressions as cad12imp,
cad26.investiment as cad26inv, cad26.impressions as cad26imp,
cad42.investiment as cad42inv, cad42.impressions as cad42imp
from (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad1-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad1
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad3-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad3
on cad1.midia = cad3.midia
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad12-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad12
on cad12.midia = cad1.midia
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad26-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad26
on cad26.midia = cad1.midia
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad42-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad42
on cad42.midia = cad1.midia;
2022-04-15 21:47:38,850 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-04-15 21:47:38,851 INFO sqlalchemy.engine.Engine ROLLBACK

TypeError: dict is not a sequence

In [29]:
sql = '''select cad1.midia, cad26.midia,cad12.midia,
cad1.investiment as cad1inv, cad1.impressions as cad1imp,
cad3.investiment as cad3inv, cad3.impressions as cad3imp,
cad12.investiment as cad12inv, cad12.impressions as cad12imp,
cad26.investiment as cad26inv, cad26.impressions as cad26imp, 
cad42.investiment as cad42inv, cad42.impressions as cad42imp
from (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad1-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad1
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad3-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad3
on cad1.midia = cad3.midia
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad12-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad12
on cad12.midia = cad1.midia
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad26-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad26
on cad26.midia = cad1.midia
full join
  (select midia,
		round(sum(cost),0) as investiment,
		round(sum(impressions),0) as impressions,
		date
		from datamarts.tb_consolidada_geral_dia tcgd
		where (date >= current_date-1)
		and (campaignname like '%cad42-%')
		and (midia in ('google','criteo','bing', 'facebook'))
		group by 1,date) cad42
on cad42.midia = cad1.midia;'''

In [41]:
pdf

                      midia  investiment  impressions        date
0                      bing       2372.0      63224.0  2022-04-14
1                  facebook       8166.0     655125.0  2022-04-14
2                    google     146628.0    6444464.0  2022-04-14
3                    criteo       2239.0     552097.0  2022-04-14
4                 onesignal          NaN          NaN  2022-04-14
5                    social          NaN          NaN  2022-04-14
6                   youtube          NaN          NaN  2022-04-14
7                     dv360          NaN          NaN  2022-04-14
8                 rtb-house          NaN          NaN  2022-04-14
9                  get-blue          NaN          NaN  2022-04-14
10                pinterest          0.0         12.0  2022-04-14
11                      gdn      21769.0    5754434.0  2022-04-14
12                     hypr          NaN          NaN  2022-04-14
13                       pd          NaN          NaN  2022-04-14
14                  m-gc-la          NaN          NaN  2022-04-14
15  cad18*0srch-wea0021*001          NaN          NaN  2022-04-14
16   cad1*0srch-brd0010*001          NaN          NaN  2022-04-14
17                      opl          NaN          NaN  2022-04-14